name: eca_packages
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  animated_text_kit: ^4.2.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.6
  getwidget: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
