name: eca_packages
description: A new Flutter package project.
version: 0.0.1+2
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  animated_text_kit: ^4.2.1
  dropdown_search: ^2.0.1
  flash: ^2.0.3+1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.6
  flutter_mobx: ^2.0.3+2
  font_awesome_flutter: ^9.2.0
  getwidget: ^2.0.4
  image_picker: ^0.8.4+4
  mobx: ^2.0.6+1
  step_progress_indicator: ^1.0.1
  transparent_image: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2

flutter:
