name: eca_packages
description: A new Flutter package project.
version: 0.0.1+2
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  # flutter: ">=1.17.0"

dependencies:
  animated_text_kit: ^4.2.1
  back_button_interceptor: ^6.0.0
  badges: ^2.0.2
  blur: ^3.0.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  dartz: ^0.10.1
  device_info_plus: ^4.1.2
  dropdown_search: ^5.0.2
  equatable: ^2.0.5
  flash: ^2.0.5
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.6
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.2
  font_awesome_flutter: ^9.0.0
  # geocoding: ^2.0.5
  # geolocator: ^9.0.2
  getwidget: ^3.0.1
  http_parser: ^4.0.1
  image_cropper: ^3.0.0
  image_picker: ^0.8.4+4
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  mobx: ^2.0.7+3
  page_transition: ^2.0.4
  package_info_plus: ^1.3.0
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  status_bar_control: ^3.2.1
  step_progress_indicator: ^1.0.1
  string_to_hex: ^0.2.2
  time_elapsed: ^0.2.6
  transparent_image: ^2.0.0
  path_provider: ^2.0.11
  path: ^1.8.2
  dio: ^4.0.6

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.0.7

flutter:
  assets:
    - assets/images/profile/
    - assets/json/cidades.json
